### ISSUE TITLE
Exceptions prevent commands not related to the plugin to fail

### ISSUE THREAD

**Issue by CC007** [Alan-Gomes/mcspring-boot#10]
When the creation of a command fails (like when the creation of certain beans needed for the command fails), any command, even the ones not related to the plugin, cause an exception to be thrown and the command to not be executed. 

Because this also affects `/reload`, `/stop` and other native bukkit commands, this issue is a high priority in my opinion.

**Comment by Alan-Gomes** [comment]
Can you provide the exception? It will make easier to debug this behavior

**Comment by CC007** [comment]
This was when I forgot to add the `@Component` annotation to my version provider:
```
[19:56:50 INFO]: CC007 issued server command: /reload
[19:56:51 INFO]: 19:56:51.016 [Server thread] ERROR dev.alangomes.springspigot.command.DefaultCommandExecutor - Unexpected exception while running /reload
picocli.CommandLine$InitializationException: Could not instantiate class com.github.cc007.headsplugin.config.PluginVersionProvider: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.cc007.headsplugin.config.PluginVersionProvider' available
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:3449)
        at picocli.CommandLine$DefaultFactory.createVersionProvider(CommandLine.java:3439)
        at picocli.CommandLine$Model$CommandSpec.updateVersionProvider(CommandLine.java:4227)
        at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:6426)
        at picocli.CommandLine$Model$CommandReflection.updateCommandAttributes(CommandLine.java:6414)
        at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:6384)
        at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:3762)
        at picocli.CommandLine.<init>(CommandLine.java:185)
        at picocli.CommandLine.toCommandLine(CommandLine.java:2388)
        at picocli.CommandLine.addSubcommand(CommandLine.java:281)
        at picocli.CommandLine.addSubcommand(CommandLine.java:266)
        at dev.alangomes.springspigot.picocli.CommandLineDefinition.lambda$build$0(CommandLineDefinition.java:39)
        at dev.alangomes.springspigot.picocli.CommandLineDefinition$$Lambda$1935/309176061.accept(Unknown Source)
        at java.util.HashMap.forEach(HashMap.java:1280)
        at dev.alangomes.springspigot.picocli.CommandLineDefinition.build(CommandLineDefinition.java:35)
        at dev.alangomes.springspigot.command.DefaultCommandExecutor.execute(DefaultCommandExecutor.java:66)
        at dev.alangomes.springspigot.command.CommandInterceptor.onPlayerCommand(CommandInterceptor.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
        at dev.alangomes.springspigot.event.SpringEventExecutor.triggerEvent(SpringEventExecutor.java:44)
        at dev.alangomes.springspigot.event.SpringEventExecutor.lambda$null$1(SpringEventExecutor.java:38)
        at dev.alangomes.springspigot.event.SpringEventExecutor$$Lambda$1934/861868233.accept(Unknown Source)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at dev.alangomes.springspigot.event.SpringEventExecutor.lambda$execute$2(SpringEventExecutor.java:38)
        at dev.alangomes.springspigot.event.SpringEventExecutor$$Lambda$1931/1780334554.run(Unknown Source)
        at dev.alangomes.springspigot.context.Context.lambda$runWithSender$2(Context.java:119)
        at dev.alangomes.springspigot.context.Context$$Lambda$1932/1155841603.apply(Unknown Source)
        at dev.alangomes.springspigot.context.Context.runWithSender(Context.java:80)
        at dev.alangomes.springspigot.context.Context.runWithSender(Context.java:118)
        at dev.alangomes.springspigot.event.SpringEventExecutor.execute(SpringEventExecutor.java:35)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1613)
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1461)
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9)
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils$$Lambda$1919/690091798.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
        at java.lang.Thread.run(Thread.java:744)
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.github.cc007.headsplugin.config.PluginVersionProvider' available
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335)
        at dev.alangomes.springspigot.picocli.SpringCommandFactory.create(SpringCommandFactory.java:16)
        at picocli.CommandLine$DefaultFactory.create(CommandLine.java:3448)
        ... 60 common frames omitted
```

**Comment by Alan-Gomes** [comment]
Fixed in https://github.com/Alan-Gomes/mcspring-boot/commit/ebec93bb6d8b8c6e768a7771df33b14d8d1f6e2c

It will be available in the next version

Thanks for reporting!
