### ISSUE TITLE
No auto configuration classes found in META-INF/spring.factories

### ISSUE THREAD

**Issue by leNicDev** [Alan-Gomes/mcspring-boot#2]
The following exception is thrown when `application.run()` is called:

```
[18:42:14 INFO]: [deinBusiness] Enabling deinBusiness v${project.version}
[18:42:14 INFO]:   .   ____          _            __ _ _
[18:42:14 INFO]:  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[18:42:14 INFO]: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[18:42:14 INFO]:  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[18:42:14 INFO]:   '  |____| .__|_| |_|_| |_\__, | / / / /
[18:42:14 INFO]:  =========|_|==============|___/=/_/_/_/
[18:42:14 INFO]:  :: Spring Boot ::
[18:42:14 INFO]: 2019-04-24 18:42:14.490  INFO 5036 --- [  Server thread] o.s.boot.SpringApplication               : Starting application on DESKTOP-XXXXXXX with PID 5036 (started by leNicDev in C:\Users\leNicDev\Desktop\spigot-1.13)

[18:42:14 INFO]: 2019-04-24 18:42:14.491  INFO 5036 --- [  Server thread] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default

[18:42:14 INFO]: 2019-04-24 18:42:14.732 ERROR 5036 --- [  Server thread] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
        at org.springframework.util.Assert.notEmpty(Assert.java:464) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:183) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:119) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:420) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:878) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:804) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:774) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:185) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:315) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at bz.dcr.deinbusiness.DeinBusinessPlugin.onEnable(DeinBusinessPlugin.java:54) ~[deinbusiness-3.0.0-jar-with-dependencies.jar:na]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) ~[spigot-1.13.2.jar:git-Spigot-f09662d-494eef4]
        at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
```

JDK Version:
```
openjdk version "1.8.0_212-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_212-1-ojdkbuild-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.4.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>bz.dcr</groupId>
    <artifactId>deinbusiness</artifactId>
    <version>3.0.0</version>
    <name>deinbusiness</name>
    <description>deinBusiness Spigot/Bukkit/Paper plugin</description>

    <!-- Repositories -->
    <repositories>
        <!-- deinCraft Repository -->
        <repository>
            <id>deincraft-repo</id>
            <url>https://maven.dtl.bz/artifactory/public</url>
        </repository>
    </repositories>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>dev.alangomes</groupId>
            <artifactId>spigot-spring-boot-starter</artifactId>
            <version>0.6.0</version>
        </dependency>

        <!-- Spigot API -->
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <version>1.13.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <!-- SlimyGuis -->
        <dependency>
            <groupId>xyz.upperlevel.spigot.gui</groupId>
            <artifactId>slimyguis</artifactId>
            <version>2.1.1</version>
            <scope>provided</scope>
        </dependency>

        <!-- ServerService -->
        <dependency>
            <groupId>de.lenic</groupId>
            <artifactId>serverservice</artifactId>
            <version>2.1.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- dcCore -->
        <dependency>
            <groupId>bz.dcr</groupId>
            <artifactId>dccore-spigot</artifactId>
            <version>1.2.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- Vault API -->
        <dependency>
            <groupId>net.milkbowl.vault</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.6</version>
            <scope>provided</scope>
        </dependency>

        <!-- HolographicDisplays API -->
        <dependency>
            <groupId>com.gmail.filoghost.holographicdisplays</groupId>
            <artifactId>holographicdisplays-api</artifactId>
            <version>2.3.2</version>
            <scope>provided</scope>
        </dependency>

        <!-- BungeeTabListPlus API -->
        <dependency>
            <groupId>codecrafter47.bungeetablistplus</groupId>
            <artifactId>bungeetablistplus-api-bukkit</artifactId>
            <version>2.7.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- Citizens API -->
        <dependency>
            <groupId>net.citizensnpcs</groupId>
            <artifactId>citizensapi</artifactId>
            <version>2.0.24-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <!-- Build Settings -->
    <build>
        <!-- Resources -->
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <!-- Plugins -->
        <plugins>
            <!-- Compiler Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>

            <!-- Assembly Plugin -->
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <!--<build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>-->
</project>
```

**Comment by Alan-Gomes** [comment]
Hello! This error is probably caused by some problem in your build configuration, I recommend you to use `maven-shade-plugin` which works well with spring dependencies.

Example:

```xml
    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>plugin.yml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <excludes>
                    <exclude>plugin.yml</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <shadedArtifactAttached>true</shadedArtifactAttached>
                    <shadedClassifierName>shaded</shadedClassifierName>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

```

**Comment by leNicDev** [comment]
@Alan-Gomes That solved my problem. Thanks for the quick response! I feel like this should be documented.
