### ISSUE TITLE
[BUG] commands that are executed by command blocks cause a NullPointerException

### ISSUE THREAD

**Issue by CC007** [Alan-Gomes/mcspring-boot#26]
This is an issue that was first posted in CC007/HeadsPluginAPI#1, but after evaluation, it seems that the culprit seems to be `ServerUtil#getSenderId(sender)`.

The issue has been spotted in minecraft 1.15 and 1.16, in both Spigot and PaperMC. The following stacktrace shows where the NPE happens:

```
ERROR: Could not pass event ServerCommandEvent to <pluginName>
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[?:1.8.0_251]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[?:1.8.0_251]
	at dev.alangomes.springspigot.context.Context.setSender(Context.java:57) ~[?:?]
	at dev.alangomes.springspigot.context.Context.runWithSender(Context.java:99) ~[?:?]
	at dev.alangomes.springspigot.context.Context.runWithSender(Context.java:139) ~[?:?]
	at dev.alangomes.springspigot.event.SpringEventExecutor.lambda$create$1(SpringEventExecutor.java:25) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-353]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-353]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.CommandDispatcher.dispatchServerCommand(CommandDispatcher.java:132) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.CommandBlockListenerAbstract.a(CommandBlockListenerAbstract.java:120) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.BlockCommand.a(BlockCommand.java:96) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.BlockCommand.tick(BlockCommand.java:83) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.IBlockData.a(IBlockData.java:218) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.WorldServer.b(WorldServer.java:777) ~[patched_1.15.2.jar:git-Paper-353]
	at com.destroystokyo.paper.server.ticklist.PaperTickList.tick(PaperTickList.java:296) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:46) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:444) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1327) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-353]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

This happens when `Context#setSender(sender)` tries to execute the following code:
```
senderRefs.put(threadId, serverUtil.getSenderId(sender));
```

This gives `null` for `BlockCommandSender`s, `ProxiedCommandSender`s, `RemoteConsoleCommandSender`s and entities that aren't also `OfflinePlayer`s.

**Comment by Alan-Gomes** [comment]
Fixed in https://github.com/Alan-Gomes/mcspring-boot/commit/6e657cadb35e08d5b3a366ac9cbfbde5826ea4bd (0.20.7), thanks!
