### ISSUE TITLE
Using Spring Data JPA

### ISSUE THREAD

**Issue by beabravedude** [Alan-Gomes/mcspring-boot#31]
I would like to know how to use Spring Data JPA with this artifact.
I have already tried using `@EnableJpaRepositores`, but no matter what I do, its not working, could you please submit a guild on how to use JPA.

Any help would be amazing!

@CC007 
@Alan-Gomes

**Comment by CC007** [comment]
I am using Spring data JPA with hibernate without issues.

**Comment by beabravedude** [comment]
That's odd how did you implement it?

**Comment by CC007** [comment]
You got a link to what you got? That way I can compare and see if there is any difference with dependencies, annotations or config.

**Comment by CC007** [comment]
Also, while I like spring in general and this plugin works fairly well, I am now trying to see if I can use another dependency injection framework (dagger2), because using Spring makes the jar file VERY big, so big that you'd need an external link on Spigotmc to upload the plugin. This causes a lot of issues with Minecraft hosts that use SpiGet to fetch the plugin or that just plainly reject using plugins that aren't uploaded to spigotmc itself.

**Comment by beabravedude** [comment]
> You got a link to what you got? That way I can compare and see if there is any difference with dependencies, annotations or config.
My pom.xml file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.beabravedude</groupId>
    <artifactId>eodcommunity</artifactId>
    <version>0.1</version>
    <packaging>jar</packaging>

    <name>EodCommunity</name>

    <description>EODCommunity Plugin</description>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.16.1-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>dev.alangomes</groupId>
            <artifactId>spigot-spring-boot-starter</artifactId>
            <version>0.20.6</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>2.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.20</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.20</version>
            <scope>runtime</scope>
        </dependency>

    </dependencies>
</project>
```
@CC007

**Comment by beabravedude** [comment]
```java
public final class EODCommunity extends JavaPlugin {

    private ConfigurableApplicationContext context;

    @Bean
    public Logger logger() {
        return getLogger();
    }

    @Override
    @SneakyThrows
    public void onEnable() {
        // Plugin startup logic
        if (!getDataFolder().exists()) {
            if (getDataFolder().mkdir()) {
                getLogger().info("Config folder created successfully!");
                saveDefaultConfig();
            } else {
                throw new Exception("Could not create config folder");
            }
        }
        context = SpringSpigotBootstrapper.initialize(this, EODCommunitySpringApp.class);
        getLogger().info("EOD Community started successfully!");
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
        if (context != null) {
            context.close();
        }
        context = null;
        getLogger().info("EOD Community stopped successfully!");
    }
}
```

this is my plugin main file
@CC007

**Comment by beabravedude** [comment]
When I run the plugin with JPA, I get the following error:

```
java.util.concurrent.ExecutionException: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.annotation.AnnotationConfigApplicationContext]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
        at dev.alangomes.springspigot.SpringSpigotBootstrapper.initialize(SpringSpigotBootstrapper.java:55) ~[?:?]
        at dev.alangomes.springspigot.SpringSpigotBootstrapper.initialize(SpringSpigotBootstrapper.java:22) ~[?:?]
        at me.beabravedude.eodcommunity.EODCommunity.onEnable(EODCommunity.java:32) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.annotation.AnnotationConfigApplicationContext]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225) ~[?:?]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[?:?]
        at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:607) ~[?:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[?:?]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) ~[?:?]
        at dev.alangomes.springspigot.SpringSpigotBootstrapper.lambda$initialize$0(SpringSpigotBootstrapper.java:53) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        ... 1 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/core/metrics/ApplicationStartup
        at org.springframework.context.support.AbstractApplicationContext.<init>(AbstractApplicationContext.java:229) ~[?:?]
        at org.springframework.context.support.GenericApplicationContext.<init>(GenericApplicationContext.java:112) ~[?:?]
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:67) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[?:?]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[?:?]
        at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:607) ~[?:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[?:?]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) ~[?:?]
        at dev.alangomes.springspigot.SpringSpigotBootstrapper.lambda$initialize$0(SpringSpigotBootstrapper.java:53) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        ... 1 more
Caused by: java.lang.ClassNotFoundException: org.springframework.core.metrics.ApplicationStartup
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot.jar:git-Spigot-9639cf7-4b9bc9d]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at org.springframework.context.support.AbstractApplicationContext.<init>(AbstractApplicationContext.java:229) ~[?:?]
        at org.springframework.context.support.GenericApplicationContext.<init>(GenericApplicationContext.java:112) ~[?:?]
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:67) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[?:?]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[?:?]
        at org.springframework.boot.SpringApplication.createApplicationContext(SpringApplication.java:607) ~[?:?]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[?:?]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) ~[?:?]
        at dev.alangomes.springspigot.SpringSpigotBootstrapper.lambda$initialize$0(SpringSpigotBootstrapper.java:53) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        ... 1 more
```
@CC007
